### ISSUE TITLE
Tables at 100% width break when centered

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/markdown.sile#53]
Converting a markdown or djot document and using the resilient.book class with default styling

![image](https://user-images.githubusercontent.com/18075640/229280737-e23b240c-ab6e-4ae4-9438-2a85e41bd824.png)

Workaround:

Tweak the style file of the document:

```
table:
  origin: "resilient.book"
  style:
    paragraph:
      after:
        vbreak: false
      align: "justify" # was "center"
      before:
        indent: false
```

Analysis:

It has to do with the table being 100% of the line, and the "center" (idem for "left", "right") adding lskip/rskip glues around it.
I'm not sure exactly why and if this point towards something deeper.
